import base64
import json

import boto3
from botocore.config import Config

from app.config.settings import get_settings

_settings = get_settings()


class BedrockService:
    def __init__(self, settings=None):
        self.settings = settings or _settings
        self.client = boto3.client(
            "bedrock-runtime",
            region_name=self.settings.aws_region,
            config=Config(retries={"max_attempts": 5, "mode": "standard"}),
        )

    def claude_detect_products_json(self, image_bytes: bytes, media_type: str = "image/jpeg") -> dict:
        """
        Returns dict parsed from Claude JSON output.
        """
        b64 = base64.b64encode(image_bytes).decode("utf-8")

        system_prompt = (
            "You are a retail product extraction engine.\n"
            "Extract distinct sellable packaged products visible in the image.\n"
            "Return STRICT JSON ONLY (no markdown, no commentary).\n"
            "Do not hallucinate weights/MRP if not clearly visible.\n"
            "Fields per product:\n"
            "- brand (string|null)\n"
            "- product_name (string)\n"
            "- net_weight: {value:number, unit:'g'|'kg'|'ml'|'l'|'pcs'} | null\n"
            "- mrp: {value:number, currency:'INR'} | null\n"
            "- confidence (0..1)\n"
            "- bbox: {x,y,w,h} normalized 0..1 (best-effort)\n"
            "- evidence: {visible_text: [string,...]}\n"
            "Output schema:\n"
            "{'products':[...]} only."
        )

        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": self.settings.claude_max_tokens,
            "temperature": self.settings.claude_temperature,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "source": {"type": "base64", "media_type": media_type, "data": b64},
                        },
                        {"type": "text", "text": system_prompt},
                    ],
                }
            ],
        }

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_claude_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        text = ""
        for block in payload.get("content", []):
            if block.get("type") == "text":
                text += block.get("text", "")

        return json.loads(text)

    def titan_outpaint(self, image_bytes: bytes, mask_bytes: bytes, prompt: str, negative: str = "") -> bytes:
        """
        Returns PNG/JPEG bytes generated by Titan Image Generator v2 outpainting.
        """
        img_b64 = base64.b64encode(image_bytes).decode("utf-8")
        mask_b64 = base64.b64encode(mask_bytes).decode("utf-8")

        body = {
            "taskType": "OUTPAINTING",
            "outPaintingParams": {
                "text": prompt,
                "negativeText": negative,
                "image": img_b64,
                "maskImage": mask_b64,
                "outPaintingMode": self.settings.titan_outpaint_mode,
            },
            "imageGenerationConfig": {
                "numberOfImages": 1,
                "height": self.settings.titan_height,
                "width": self.settings.titan_width,
                "cfgScale": self.settings.titan_cfg_scale,
                "quality": self.settings.titan_quality,
            },
        }

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_titan_image_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        images = payload.get("images", [])
        if not images:
            raise RuntimeError(f"No images in Titan response: {payload.keys()}")

        out_bytes = base64.b64decode(images[0])
        return out_bytes
