import base64
import json
import logging

import boto3
from botocore.config import Config

from app.config.settings import get_settings

_settings = get_settings()
logger = logging.getLogger(__name__)


class BedrockService:
    def __init__(self, settings=None):
        self.settings = settings or _settings
        kwargs: dict = {
            "region_name": self.settings.aws_region,
            "config": Config(
                retries={"max_attempts": 5, "mode": "standard"},
                read_timeout=300,
            ),
        }
        if self.settings.aws_access_key_id and self.settings.aws_secret_access_key:
            kwargs["aws_access_key_id"] = self.settings.aws_access_key_id
            kwargs["aws_secret_access_key"] = self.settings.aws_secret_access_key
        self.client = boto3.client("bedrock-runtime", **kwargs)

    def claude_detect_products_json(self, image_bytes: bytes, media_type: str = "image/jpeg") -> dict:
        """
        Returns dict parsed from Claude JSON output.
        """
        b64 = base64.b64encode(image_bytes).decode("utf-8")

        system_prompt = (
            "You are a retail product extraction engine.\n"
            "Extract distinct sellable packaged products visible in the image.\n"
            "Return STRICT JSON ONLY (no markdown, no commentary).\n"
            "Do not hallucinate weights/MRP if not clearly visible.\n"
            "Fields per product:\n"
            "- brand (string|null)\n"
            "- product_name (string)\n"
            "- net_weight: {value:number, unit:'g'|'kg'|'ml'|'l'|'pcs'} | null\n"
            "- mrp: {value:number, currency:'INR'} | null\n"
            "- confidence (0..1)\n"
            "- bbox: {x,y,w,h} normalized 0..1 (best-effort)\n"
            "- evidence: {visible_text: [string,...]}\n"
            "Output schema:\n"
            "{'products':[...]} only."
        )

        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": self.settings.claude_max_tokens,
            "temperature": self.settings.claude_temperature,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "source": {"type": "base64", "media_type": media_type, "data": b64},
                        },
                        {"type": "text", "text": system_prompt},
                    ],
                }
            ],
        }

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_claude_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        text = ""
        for block in payload.get("content", []):
            if block.get("type") == "text":
                text += block.get("text", "")

        return json.loads(text)

    # ------------------------------------------------------------------
    # Titan Image Generator v2 (legacy — kept for backward compatibility)
    # ------------------------------------------------------------------

    def titan_outpaint(self, image_bytes: bytes, mask_bytes: bytes, prompt: str, negative: str = "") -> bytes:
        """
        Returns PNG/JPEG bytes generated by Titan Image Generator v2 outpainting.
        DEPRECATED: Use nova_canvas_outpaint() instead — 50% cheaper, better quality.
        """
        img_b64 = base64.b64encode(image_bytes).decode("utf-8")
        mask_b64 = base64.b64encode(mask_bytes).decode("utf-8")

        body = {
            "taskType": "OUTPAINTING",
            "outPaintingParams": {
                "text": prompt,
                "negativeText": negative,
                "image": img_b64,
                "maskImage": mask_b64,
                "outPaintingMode": self.settings.titan_outpaint_mode,
            },
            "imageGenerationConfig": {
                "numberOfImages": 1,
                "height": self.settings.titan_height,
                "width": self.settings.titan_width,
                "cfgScale": self.settings.titan_cfg_scale,
                "quality": self.settings.titan_quality,
            },
        }

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_titan_image_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        images = payload.get("images", [])
        if not images:
            raise RuntimeError(f"No images in Titan response: {payload.keys()}")

        out_bytes = base64.b64decode(images[0])
        return out_bytes

    # ------------------------------------------------------------------
    # Amazon Nova Canvas (recommended — $0.04/image vs $0.08 for Titan)
    # ------------------------------------------------------------------

    def nova_canvas_outpaint(
        self,
        image_bytes: bytes,
        mask_bytes: bytes | None = None,
        mask_prompt: str | None = None,
        prompt: str = "",
        negative: str = "",
    ) -> bytes:
        """Generate a studio image via Nova Canvas outpainting.

        Supports two masking modes:
          - **mask_bytes**: Provide a pre-built mask image (same as Titan).
            White = keep, Black = repaint.
          - **mask_prompt**: Describe what to keep in natural language
            (e.g. "product package"). Nova Canvas generates the mask
            automatically — no PIL mask logic needed.

        Exactly one of *mask_bytes* or *mask_prompt* must be provided.

        Note: For OUTPAINTING, width/height must NOT be set in
        imageGenerationConfig per AWS docs.
        """
        if not mask_bytes and not mask_prompt:
            raise ValueError("Provide either mask_bytes or mask_prompt")
        if mask_bytes and mask_prompt:
            raise ValueError("Provide mask_bytes OR mask_prompt, not both")

        img_b64 = base64.b64encode(image_bytes).decode("utf-8")

        outpainting_params: dict = {
            "image": img_b64,
            "outPaintingMode": "PRECISE",
        }

        if mask_bytes:
            outpainting_params["maskImage"] = base64.b64encode(mask_bytes).decode("utf-8")
        else:
            outpainting_params["maskPrompt"] = mask_prompt

        if prompt:
            outpainting_params["text"] = prompt
        if negative:
            outpainting_params["negativeText"] = negative

        body = {
            "taskType": "OUTPAINTING",
            "outPaintingParams": outpainting_params,
            "imageGenerationConfig": {
                "numberOfImages": 1,
                "quality": self.settings.nova_canvas_quality,
                "cfgScale": self.settings.nova_canvas_cfg_scale,
            },
        }

        logger.info("Nova Canvas OUTPAINTING request (mask_mode=%s)",
                    "image" if mask_bytes else "prompt")

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_nova_canvas_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        if payload.get("error"):
            raise RuntimeError(f"Nova Canvas error: {payload['error']}")

        images = payload.get("images", [])
        if not images:
            raise RuntimeError(f"No images in Nova Canvas response: {payload.keys()}")

        return base64.b64decode(images[0])

    def nova_canvas_background_removal(self, image_bytes: bytes) -> bytes:
        """Remove background from an image using Nova Canvas.

        Returns a PNG with full 8-bit transparency — the product is
        cleanly isolated with no background. Perfect for compositing
        onto a white studio background afterwards.

        This is the simplest operation: just pass the image, get back
        a transparent PNG. No masks, no prompts needed.
        """
        img_b64 = base64.b64encode(image_bytes).decode("utf-8")

        body = {
            "taskType": "BACKGROUND_REMOVAL",
            "backgroundRemovalParams": {
                "image": img_b64,
            },
        }

        logger.info("Nova Canvas BACKGROUND_REMOVAL request")

        resp = self.client.invoke_model(
            modelId=self.settings.bedrock_nova_canvas_model_id,
            body=json.dumps(body),
            accept="application/json",
            contentType="application/json",
        )

        payload = json.loads(resp["body"].read())
        if payload.get("error"):
            raise RuntimeError(f"Nova Canvas error: {payload['error']}")

        images = payload.get("images", [])
        if not images:
            raise RuntimeError(f"No images in Nova Canvas response: {payload.keys()}")

        return base64.b64decode(images[0])
